<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Knight Frank AED 200000TC AppliesA resi_311f8a</name>
   <tag></tag>
   <elementGuidId>70538156-bbbe-443d-bff1-762e82d67012</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//owl-carousel[@id='propertyForm']/owl-carousel-child/div/div/div/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>property-info-wrap</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Knight Frank AED 2,000.00*T&amp;C AppliesA residential &amp; commercial property consultantFounded in 1896; Middle East presence from 2008Leading independent real estate consultancy, Dubai</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;propertyForm&quot;)/owl-carousel-child[@class=&quot;owl-theme sliding owl-carousel owl-loaded owl-drag ng-star-inserted&quot;]/div[@class=&quot;owl-stage-outer&quot;]/div[@class=&quot;owl-stage&quot;]/div[@class=&quot;owl-item active&quot;]/div[@class=&quot;col-md-12 item ng-star-inserted&quot;]/div[1]/div[@class=&quot;property-info-wrap&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//owl-carousel[@id='propertyForm']/owl-carousel-child/div/div/div/div/div/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='INDEPENDENT REAL ESTATE VALUATOR (FEE INVOLVED)'])[1]/following::div[8]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CHIRAGH (FREE ESTIMATES)'])[1]/following::div[10]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//owl-carousel-child/div/div/div/div/div/div</value>
   </webElementXpaths>
</WebElementEntity>
