<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Chiragh Real Estate Auctions_fas fa-bars _aebcba</name>
   <tag></tag>
   <elementGuidId>c0a75baf-811a-4e94-a0ab-58f76ebaac87</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fas fa-bars btn-demo</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>#financemodal</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>modal</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-layout[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;main-container&quot;]/app-finance[@class=&quot;ng-star-inserted&quot;]/app-agent[@class=&quot;ng-star-inserted&quot;]/app-topup[@class=&quot;ng-star-inserted&quot;]/section[@class=&quot;common-table-section ng-star-inserted&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row dashboard-tbl-wrap&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;table-responsive&quot;]/table[@class=&quot;table dashboard-tbl&quot;]/tbody[1]/tr[@class=&quot;ng-star-inserted&quot;]/td[2]/div[@class=&quot;new-leads&quot;]/div[@class=&quot;menu-wrapper&quot;]/a[@class=&quot;fas fa-bars btn-demo&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/a</value>
   </webElementXpaths>
</WebElementEntity>
