<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_BUY SELLRENTHELP CENTER ENG  ARA(UAE)EN_9ab9fd</name>
   <tag></tag>
   <elementGuidId>d0f7af5f-632f-497e-b9c6-3581a61a5876</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//nav[@id='banner']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>container-fluid</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>BUY SELLRENTHELP CENTER ENG  ARA(UAE)ENG69 Notifications  Your property has been submitted successfully  Property ID: 39617 2 days ago Your property has been submitted successfully  Property ID: 39616 2 days ago Your bid has been placed  Property ID: 39541 2 days ago Your seller security deposit has been refunded.  Property ID: 38986 13 days ago Your seller security deposit has been refunded.  Property ID: 39533 13 days ago Your seller security deposit has been refunded.  Property ID: 39537 15 days ago Your property has been submitted successfully  Property ID: 39516 20 days ago Your property has been submitted successfully  Property ID: 39515 20 days ago Your property has been submitted successfully  Property ID: 39510 20 days ago Your property has been submitted successfully  Property ID: 39509 20 days ago Your property has been submitted successfully  Property ID: 39437 a month ago Your property has been submitted successfully  Property ID: 39434 a month ago Your property has been submitted successfully  Property ID: 39434 a month ago Your property has been submitted successfully  Property ID: 39434 a month ago Your property has been submitted successfully  Property ID: 39433 a month ago Your property has been submitted successfully  Property ID: 39431 a month ago Your property has been submitted successfully  Property ID: 39430 a month ago Your property has been submitted successfully  Property ID: 39430 a month ago Your property is marked as unsold and already been moved to unsold tab.  Property ID: 39306 a month ago Property auction closed  Property ID: 39306 a month ago Your property is marked as unsold and already been moved to unsold tab.  Property ID: 38966 a month ago Your seller security has been forfeited  Property ID: 38966 a month ago Buyer has rejected his offer  Property ID: 38966 a month ago Property auction closed  Property ID: 38966 a month ago Your property is Live  Property ID: 38966 a month ago Your property has been submitted successfully  Property ID: 39378 a month ago Your property has been submitted successfully  Property ID: 39361 a month ago Your property has been submitted successfully  Property ID: 39358 a month ago Your property has been submitted successfully  Property ID: 39340 a month ago Your property is Live  Property ID: 39306 a month agoGo to inboxHI AutoChiragh Logout</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;banner&quot;)/div[@class=&quot;container-fluid&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='banner']/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/div</value>
   </webElementXpaths>
</WebElementEntity>
