<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>BankOption1</name>
   <tag></tag>
   <elementGuidId>acb996e0-1777-4a59-92e5-217c0b3e5fa5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/app-root/app-layout/section/div/div[3]/app-wallet/div/div[2]/app-make-transaction/div[2]/app-top-up/form/div[3]/div[1]/div/div[1]/select/option[2]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/app-root/app-layout/section/div/div[3]/app-wallet/div/div[2]/app-make-transaction/div[2]/app-top-up/form/div[3]/div[1]/div/div[1]/select/option[2]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>option</value>
   </webElementProperties>
</WebElementEntity>
