<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>currency_EUR</name>
   <tag></tag>
   <elementGuidId>ef6e1d45-b006-47ed-98c1-c01971441c24</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html/body/app-root/app-layout/section/div/div[3]/app-wallet/div/div[2]/app-make-transaction/div[2]/app-top-up/form/div[1]/div[2]/div/div[2]/div/select/option[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/app-root/app-layout/section/div/div[3]/app-wallet/div/div[2]/app-make-transaction/div[2]/app-top-up/form/div[1]/div[2]/div/div[2]/div/select/option[3]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>option</value>
   </webElementProperties>
</WebElementEntity>
