<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SPA</name>
   <tag></tag>
   <elementGuidId>ba05bc00-9dc6-4d3d-bdfd-cdea23760605</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/app-root/app-core/app-sell/div/div/app-property-detail/form/div[7]/div[1]/div[1]/div[3]/app-upload-file/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/app-root/app-core/app-sell/div/div/app-property-detail/form/div[7]/div[1]/div[1]/div[3]/app-upload-file/div/input</value>
   </webElementProperties>
</WebElementEntity>
